services:
  app:
    image: "${IMAGE_REPO:-ghcr.io/certstone/logto-account-portal}:${IMAGE_TAG:-latest}"
    ports:
      - "1742:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      CONFIG_DIR: /app/deploy
      CONFIG_ENV_FILE: .env
    volumes:
      - ./.env:/app/deploy/.env:ro
      - ./deploy/features.yaml:/app/deploy/features.yaml:ro
      - ./deploy/services.yaml:/app/deploy/services.yaml:ro
      # - ./deploy/icons:/app/public/icons:ro
    restart: unless-stopped
